# Generated by Django 5.0.8 on 2024-11-22 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Название сервера"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=25, unique=True, verbose_name="Слаг"),
                ),
                ("max_online", models.IntegerField()),
            ],
            options={
                "verbose_name": "Сервер",
                "verbose_name_plural": "Серверы",
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название достижения"),
                ),
                ("description", models.TextField(verbose_name="Описание достижения")),
                (
                    "earned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название ивента"),
                ),
                ("description", models.TextField(verbose_name="Описание ивента")),
                ("date", models.DateField(verbose_name="Дата проведения")),
                ("time", models.TimeField(verbose_name="Время начала")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный ивент"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Ивент",
                "verbose_name_plural": "Ивенты",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Название новости"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=10000, verbose_name="Содержание новости"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/MinecraftLogo.png",
                        upload_to="media/news/%Y/%m/%d/",
                        verbose_name="Изображение новости",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата обновления"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Слаг")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликована"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="serv",
                        to="minecraft.servers",
                        verbose_name="Наименование сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
