# Generated by Django 5.0.8 on 2024-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("bot_response", models.TextField()),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
