# Generated by Django 5.0.8 on 2024-12-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0002_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
