# Generated by Django 5.0.8 on 2024-12-09 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0003_delete_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="coordinates",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Координаты",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/images",
                verbose_name="Картинка 1",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/images",
                verbose_name="Картинка 2",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/images",
                verbose_name="Картинка 3",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Место проведения",
            ),
        ),
    ]
