# Generated by Django 5.0.8 on 2024-12-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0004_event_author_event_coordinates_event_image1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Achievement",
        ),
    ]
