# Generated by Django 5.0.8 on 2024-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0005_delete_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("started", "Начат"),
                    ("finished", "Закончен"),
                ],
                default="waiting",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Описание ивента"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=40, verbose_name="Название ивента"),
        ),
    ]
