# Generated by Django 5.0.8 on 2024-12-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0006_event_status_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("started", "Начат"),
                    ("finished", "Закончен"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
