# Generated by Django 5.0.8 on 2024-12-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0007_alter_event_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
    ]
