# Generated by Django 5.0.8 on 2024-12-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0008_remove_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "В ожидании"),
                    ("started", "Начат"),
                    ("finished", "Закончен"),
                ],
                default="waiting",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
