# Generated by Django 5.1.3 on 2024-11-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_donate_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donate",
            options={"verbose_name": "Донат", "verbose_name_plural": "Донаты"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
