# Generated by Django 5.0.8 on 2024-11-26 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_donate_options_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True,
                default="Не указан",
                max_length=100,
                null=True,
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True,
                default="Описание отсутствует",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_rating",
            field=models.IntegerField(default=0, verbose_name="Социальный рейтинг"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="donate",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="don",
                to="user.donate",
                verbose_name="Донат пользователя",
            ),
        ),
    ]
