# Generated by Django 5.0.8 on 2024-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_profile_city_profile_description_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
