# Generated by Django 5.0.8 on 2024-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_profile_managers_remove_profile_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Никнейм"
            ),
        ),
    ]
