# Generated by Django 5.0.8 on 2024-12-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_profile_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название достижения"),
                ),
                ("description", models.TextField(verbose_name="Описание достижения")),
                (
                    "earned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="achivements/",
                        verbose_name="Изображение достижения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Наименование роли"
                    ),
                ),
                ("responsobility", models.IntegerField(verbose_name="Сила роли")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="roles/", verbose_name="Изображение роли"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роли",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="achievement",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="achive",
                to="user.achievement",
                verbose_name="Достижение пользователя",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role",
                to="user.roles",
                verbose_name="Роль пользователя",
            ),
        ),
    ]
