# Generated by Django 5.0.8 on 2024-12-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_achievement_roles_profile_achievement_profile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Сonviction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название судимости"),
                ),
                ("description", models.TextField(verbose_name="Описание судимости")),
                (
                    "earned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="conviction /",
                        verbose_name="Изображение судимсоти",
                    ),
                ),
            ],
            options={
                "verbose_name": "Судимость",
                "verbose_name_plural": "Судимости",
            },
        ),
        migrations.RenameModel(
            old_name="Roles",
            new_name="Role",
        ),
        migrations.AddField(
            model_name="profile",
            name="сonviction",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Сonvict",
                to="user.сonviction",
                verbose_name="Судимости пользователя",
            ),
        ),
    ]
