# Generated by Django 5.0.8 on 2024-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_сonviction_rename_roles_role_profile_сonviction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conviction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название судимости"),
                ),
                ("description", models.TextField(verbose_name="Описание судимости")),
                (
                    "earned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="conviction/",
                        verbose_name="Изображение судимсоти",
                    ),
                ),
            ],
            options={
                "verbose_name": "Судимость",
                "verbose_name_plural": "Судимости",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="сonviction",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="achievement",
        ),
        migrations.AddField(
            model_name="profile",
            name="conviction",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="Convict",
                to="user.conviction",
                verbose_name="Судимости пользователя",
            ),
        ),
        migrations.DeleteModel(
            name="Сonviction",
        ),
        migrations.AddField(
            model_name="profile",
            name="achievement",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="achive",
                to="user.achievement",
                verbose_name="Достижение пользователя",
            ),
        ),
    ]
