# Generated by Django 5.0.8 on 2024-12-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_profile_conviction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="conviction",
            field=models.ManyToManyField(
                default=None,
                related_name="convictions",
                to="user.conviction",
                verbose_name="Судимости пользователя",
            ),
        ),
    ]
