# Generated by Django 5.0.8 on 2024-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_profile_conviction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="conviction",
            field=models.ManyToManyField(
                related_name="conviction",
                to="user.conviction",
                verbose_name="Судимости пользователя",
            ),
        ),
    ]
