# Generated by Django 5.0.8 on 2024-12-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0009_event_status"),
        ("user", "0021_alter_profile_conviction"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="passed_events",
            field=models.ManyToManyField(
                blank=True, related_name="passed_by", to="minecraft.event"
            ),
        ),
    ]
