# Generated by Django 5.0.8 on 2025-01-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_profile_passed_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="achievement",
            field=models.ManyToManyField(
                blank=True,
                related_name="achive",
                to="user.achievement",
                verbose_name="Достижение пользователя",
            ),
        ),
    ]
